### PR TITLE
Fixes the inseration of greater than character (#44)

### PR DESCRIPTION
**Pull request by marlun**
I havn't tested this very much but it works in my simple tests. Would really appreciate some help testing this out and also some tips on how I should change the commit message.

### CODE REVIEW

**Comment by sukima** [comment]
I think this approach is correct. I'd tend to defer to your testing so . I'm going to merge anyway. Will revert if people complain.

Fixing your commit message is a s simple as `git commit --amend` then a `git push -f`

**Comment by marlun** [comment]
Yes but I'm having a hard time thinking of a good commit message :)

**Comment by marlun** [comment]
Sorry for the spamming commits, fixed the message first and then added the "Fixes".

**Comment by sukima** [comment]
That commit message is awesome!!!

**Comment by marlun** [comment]
Glad I could help, lets hope it works for everyone else too :)

**Pull request merged**
